export const ActionTypes={
    SET_CUSTOMERS : "SET_CUSTOMERS",
    SELECTED_CUSTOMER:"SELECTED_CUSTOMER",
    ADD_CUSTOMER:"ADD_CUSTOMER",
    LOGIN_USER:"LOGIN_USER",
    FETCH_CLTS:"FETCH_CLTS",
    REMOVE_SELECTED_CUSTOMER:"REMOVE_SELECTED_CUSTOMER",
    FETCH_CLTS_Date:"FETCH_CLTS_Date",
    GET_ALL_CLTS:"GET_ALL_CLTS"
};